name: "hola mundo"

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hacemos algo"
      - run: echo "Hacemos algo"
      - run: echo "Hacemos algo"
